# Generated by Django 4.1.2 on 2023-01-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_imagego'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registergo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Age', models.IntegerField()),
                ('Place', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=8)),
                ('Imagename', models.CharField(max_length=30)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
